name: Rust

on:
  push:
    branches: ["master"]
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  test_nightly:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          # Windows interacts badly with private keys
          # - windows-latest
          - macOS-latest
        toolchain:
          - nightly
        cargo_flags:
          - "--all-features"
    steps:
      - name: Checkout source code
        uses: actions/checkout@v6

      - name: Add private rumple key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.RUMPLE_KEY }}

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.toolchain }}
          override: true

      - name: Build tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --workspace --no-run ${{ matrix.cargo_flags }}

      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --workspace ${{ matrix.cargo_flags }}
